### ISSUE TITLE
error running marionette

### ISSUE THREAD

**Issue by hmntptwl** [CuriousLearner/marionette-intro#1]
hi @CuriousLearner 
I tried |mach run -marionette|, now it listens on port 2828. I created a file marionette.py  as:
`
from marionette import Marionette
`
`
client = Marionette('localhost', port=2828)
`

Now `python marionette.py` gives an error as:

Traceback (most recent call last):
  File "marionette.py", line 1, in <module>
    from marionette import Marionette
  File "/home/hemant/.local/lib/python2.7/site-packages/marionette/__init__.py", line 18, in <module>
    from logging import ERROR, Formatter, StreamHandler, getLogger
ImportError: cannot import name ERROR

Could you please help me with this !

**Comment by CuriousLearner** [comment]
Did you have a virtualenv setup with all the dependencies installed?

How are you trying to run marionette?

**Comment by hmntptwl** [comment]
I have to write a UI test for some chrome stuff in firefox. So aren't things already set up there for this task in mozilla-central iteself !

**Comment by hmntptwl** [comment]
nvm, got it anyway :)

**Comment by CuriousLearner** [comment]
If you got the answer, it's always a good idea to describe the solution. :)

Might help others who get to this issue in future.

**Comment by hmntptwl** [comment]
As told by you, I created a virtualenv and installed necessary dependencies. Actually real problem was my network giving ssl error. So changed it.
More stuff here: https://dxr.mozilla.org/mozilla-central/source/testing/marionette/client/docs
